// Generated by CoffeeScript 1.4.0
(function() {
  var Clock;

  if (!String.prototype.trim) {
    String.prototype.trim = function() {
      return this.replace(/^\s+|\s+$/g, '');
    };
  }

  Clock = (function() {

    function Clock() {
      var args, hours, minutes, seconds, _ref;
      if (arguments.lenth === 0) {
        args = {};
      } else {
        args = Array.prototype.shift.call(arguments);
      }
      if (args.date && !(args.date instanceof Date)) {
        throw "args.date is not an instance of Date";
      } else {
        this.date = new Date();
      }
      if (args.time) {
        _ref = args.time.split(':'), hours = _ref[0], minutes = _ref[1], seconds = _ref[2];
        this.date.setHours(hours);
        this.date.setMinutes(minutes);
        this.date.setSeconds(seconds);
      }
      this.epoch = this.date.getTime();
      this.refresh = 1000;
      this.tock();
    }

    Clock.prototype.pad = function(i) {
      return (i < 10 ? "0" : "") + i;
    };

    Clock.prototype.tick = function() {
      return this.date = new Date(this.epoch);
    };

    Clock.prototype.tock = function() {
      var t;
      t = this;
      return setInterval((function() {
        t.epoch += t.refresh;
        return t.tick();
      }), this.refresh);
    };

    Clock.prototype.getTime = function() {
      return [this.pad(this.date.getHours()), this.pad(this.date.getMinutes()), this.pad(this.date.getSeconds())].join(':');
    };

    return Clock;

  })();

}).call(this);
