// Generated by CoffeeScript 1.4.0
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  if (!String.prototype.trim) {
    String.prototype.trim = function() {
      return this.replace(/^\s+|\s+$/g, '');
    };
  }

  root.Clock = (function() {

    function Clock() {
      var args;
      if (!(this instanceof arguments.callee)) {
        throw new Error('Constructor called as a function');
      }
      if (arguments.length === 0) {
        args = {};
      } else {
        args = Array.prototype.shift.call(arguments);
      }
      if (typeof args !== 'object') {
        throw new Error('args is not an object');
      }
      if (args.date && args.time) {
        throw new Error('Do not set args.date and args.time');
      }
      if (args.date && !(args.date instanceof Date)) {
        throw new Error('args.date is not an instance of Date');
      } else {
        this.date = new Date();
      }
      if (args.time) {
        if (args.time.match(/^(0?[0-9]|1[0-9]|2[0-3]):([0-5]\d):([0-5]\d)$/)) {
          this.date.setHours(RegExp.$1);
          this.date.setMinutes(RegExp.$2);
          this.date.setSeconds(RegExp.$3);
        } else if (args.time.match(/^(0?[1-9]|1[0-2]):([0-5]\d):([0-5]\d)\s+([AP]M)$/i)) {
          this.date.setHours((RegExp.$4.toLowerCase() === 'pm' ? 12 : 0) + parseInt(RegExp.$1, 10));
          this.date.setMinutes(RegExp.$2);
          this.date.setSeconds(RegExp.$3);
        } else {
          throw new Error('args.time is not a valid time');
        }
      }
      this.start = (new Date).getTime();
      this.epoch = this.date.getTime();
      this.time = 0;
      if (args.delay && typeof args.delay === 'number') {
        this.delay = args.delay;
      } else {
        this.delay = 1000;
      }
      this.tick();
    }

    Clock.prototype.pad = function(i) {
      return (i < 10 ? "0" : "") + i;
    };

    Clock.prototype.stop = function() {
      return clearTimeout(this.id);
    };

    Clock.prototype.tick = function() {
      var diff, that;
      diff = (new Date).getTime() - this.start - this.time;
      that = this;
      return that.id = setTimeout((function() {
        that.epoch += that.delay;
        that.time += that.delay;
        that.date = new Date(that.epoch);
        return that.tick();
      }), this.delay - diff);
    };

    Clock.prototype.getTime = function() {
      return [this.pad(this.date.getHours()), this.pad(this.date.getMinutes()), this.pad(this.date.getSeconds())].join(':');
    };

    return Clock;

  })();

}).call(this);
